DemoCoreWebApplication/DemoCoreWebApplication/Models/ErrorViewModel.cs
using System;

namespace DemoCoreWebApplication.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DemoCoreWebApplication/DemoCoreWebApplication/Models/OpenIAMUserInfoModel.cs
namespace DemoCoreWebApplication.Models
{
    public class OpenIAMUserInfoModel
    {
        public string id { get; set; }
        public string beanType { get; set; }
        public string operation { get; set; }
        public string classification { get; set; }
        public string middleInit { get; set; }
        public string accessRightIds { get; set; }
        public string name { get; set; }
        public string phone { get; set; }
        public string email { get; set; }
        public string userStatus { get; set; }
        public string accountStatus { get; set; }
        public string principal { get; set; }
        public string organization { get; set; }
        public string department { get; set; }
        public string division { get; set; }
        public string title { get; set; }
        public string employeeId { get; set; }
        public string startDate { get; set; }
        public string accessRightStartDate { get; set; }
        public string accessRightEndDate { get; set; }
        public string organizations { get; set; }
        public string location { get; set; }
        public string firstName { get; set; }
        public string lastName { get; set; }
        public string nickname { get; set; }
        public string birthdate { get; set; }
        public string birthdateAsStr { get; set; }
        public string maidenName { get; set; }
        public string suffix { get; set; }
        public string sex { get; set; }
        public string gender { get; set; }
        public string jobCodeId { get; set; }
        public string prefix { get; set; }
        public string prefixLastName { get; set; }
        public string partnerName { get; set; }
        public string locationCd { get; set; }
        public string userTypeInd { get; set; }
        public string employeeTypeId { get; set; }
        public string employeeTypeName { get; set; }
        public string costCenter { get; set; }
        public string alternateContactId { get; set; }
        public string alternativeStartDate { get; set; }
        public string alternativeEndDate { get; set; }
        public string certificationDelegateId { get; set; }
        public string certificationDelegateEndDate { get; set; }
        public string certificationDelegateStartDate { get; set; }
        public string supervisorMdTypeName { get; set; }
        public string accountTypeName { get; set; }
        public bool visible { get; set; }
        public string relationship { get; set; }
        public string mdTypeId { get; set; }
        public string applicationNames { get; set; }
        public string accessRightStartDateStr { get; set; }
        public string accessRightEndDateStr { get; set; }
    }
}

DemoCoreWebApplication/DemoCoreWebApplication/Models/UserSearchModel.cs
namespace DemoCoreWebApplication.Models
{
    public class UserSearchModel
    {
        public string LastName { get; set; }
    }
}

DemoCoreWebApplication/DemoCoreWebApplication/Controllers/ClaimsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DemoCoreWebApplication.Controllers
{
    [Authorize]
    public class ClaimsController : Controller
    {
        public IActionResult Index()
        {
            var userClaims = User.Identity as System.Security.Claims.ClaimsIdentity;

            //You get the user's first and last name below:
            ViewBag.Name = userClaims?.FindFirst("name")?.Value;

            // The 'preferred_username' claim can be used for showing the username
            ViewBag.Username = userClaims?.FindFirst("preferred_username")?.Value;

            // The subject/ NameIdentifier claim can be used to uniquely identify the user across the web
            ViewBag.Subject = userClaims?.FindFirst(System.Security.Claims.ClaimTypes.NameIdentifier)?.Value;

            // TenantId is the unique Tenant Id - which represents an organization in Azure AD
            ViewBag.Email = userClaims?.FindFirst("email")?.Value;

            return View();
        }
    }
}

DemoCoreWebApplication/DemoCoreWebApplication/Controllers/HomeController.cs
using DemoCoreWebApplication.Enteties;
using DemoCoreWebApplication.Models;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication.OpenIdConnect;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using RestSharp;
using RestSharp.Authenticators;
using System.Diagnostics;
using System.Threading.Tasks;

namespace DemoCoreWebApplication.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly OIDCConfig _config;

        public HomeController(ILogger<HomeController> logger, IOptions<OIDCConfig> config)
        {
            _logger = logger;
            _config = config.Value;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public async Task Login(string returnUrl = "/")
        {
            await HttpContext.ChallengeAsync(OpenIdConnectDefaults.AuthenticationScheme, new AuthenticationProperties() { RedirectUri = returnUrl });
        }

        public async Task Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            await HttpContext.SignOutAsync(OpenIdConnectDefaults.AuthenticationScheme);
        }

        [Authorize]
        public IActionResult Secure()
        {
            return View();
        }

        [Authorize]
        public ActionResult Search()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public async Task<ActionResult> Search(UserSearchModel model)
        {
            string searchEndpoint = _config.SearchEndpoint;
            RestClient restClient = new RestClient(searchEndpoint);
            var result = Request.Cookies;
            string token = await HttpContext.GetTokenAsync("access_token");
            restClient.Authenticator = new JwtAuthenticator(token);
            RestRequest restRequest = new RestRequest(Method.POST);
            SearchEntity searchEntity = new SearchEntity();
            searchEntity.lastName = model.LastName;
            restRequest.AddJsonBody(searchEntity);
            var restResponse = await restClient.ExecuteAsync<SearchUserResponse>(restRequest);
            ViewBag.UserList = restResponse.Data.beans;
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DemoCoreWebApplication/DemoCoreWebApplication/Views/Claims/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<h2>User info</h2>

<body>
    <h3>Main Claims:</h3>
    <table>
        <tr><td>Name</td><td>@ViewBag.Name</td></tr>
        <tr><td>Username</td><td>@ViewBag.Username</td></tr>
        <tr><td>Subject</td><td>@ViewBag.Subject</td></tr>
        <tr><td>Email</td><td>@ViewBag.Email</td></tr>
    </table>
    <br />
    <h3>All Claims:</h3>
    <table>
        @foreach (var claim in User.Claims)
        {
            <tr><td>@claim.Type</td><td>@claim.Value</td></tr>
        }
    </table>
</body>

DemoCoreWebApplication/DemoCoreWebApplication/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>

    @if (User.Identity.IsAuthenticated)
    {
        <div>Hello @User.FindFirst("preferred_username").Value</div>

        <a class="nav-link text-dark" asp-area="" asp-controller="Claims" asp-action="Index">See Your Claims</a>
        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Search">User search</a>
    }
</div>

DemoCoreWebApplication/DemoCoreWebApplication/Views/Home/Search.cshtml
@model DemoCoreWebApplication.Models.UserSearchModel
@{
    ViewBag.Title = "User Search";
}

<h2>User Search</h2>

@using (Html.BeginForm("Search", "Home", FormMethod.Post))
{
    @Html.TextBoxFor(model => model.LastName)
    <button type="submit">Search by last name</button>
}
@if (ViewBag.UserList != null)
{
    foreach (var item in ViewBag.UserList)
    {
        <div>Id: @item.id</div>
        <div>Principal: @item.principal</div>
        <div>Name: @item.name</div>
        <div>FirstName: @item.firstName</div>
        <div>LastName: @item.lastName</div>
        <br />
    }
}

DemoCoreWebApplication/DemoCoreWebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DemoCoreWebApplication</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DemoCoreWebApplication</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        @if (!User.Identity.IsAuthenticated)
                        {
                            <!-- If the user is not authenticated, display the sign-in button -->
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Logout</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - DemoCoreWebApplication - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>